name: Last.fm Cover Test

on:
  push:
    branches: [cover-test]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: cover-test
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: pip install requests
          
      - name: Generate and verify widget
        run: |
          python scripts/generate_svg.py
          echo "=== Проверка файла ==="
          ls -la assets/
          head -n 3 assets/lastfm_widget.svg
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
          
      - name: Commit result
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/lastfm_widget.svg
          git commit -m "Test: cover image update [skip ci]" || exit 0
          git push origin cover-test
